### PR TITLE
Restart a watch based on the current resource version.

### PR DESCRIPTION
**Pull request by mrglavas**

### CODE REVIEW

**Comment by mrglavas** [comment]
Resolves: https://github.com/kappnav/issues/issues/136

**Review by paulben — APPROVED** [review]
Looks like your branch is a few commits behind master.

**Comment by mrglavas** [comment]
@paulben Would have to resolve a merge conflict if that were an issue. The files changed don't overlap.

**Comment by mrglavas** [comment]
It seems to have merged cleanly with master.

**Pull request closed without merging**
